[workspace]
members = [
    "crates/kaka-core",
    "crates/kaka-treesitter",
    "crates/kaka",
    "xtask"
]
default-members = ["crates/kaka"]

#[profile.dev.package.'*']
#opt-level = 3
#
#[profile.dev]
#opt-level = 1
#
