[package]
name = "stud-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
ropey = "1.5.0"
thiserror = "1.0.31"
